jangwon3828/Algorithm_Competition-Study

2주차/2주차_우진/README.md
2주차/2주차_우진/단지번호붙이기.java
2주차/2주차_우진/연결 요소의 개수.java
2주차/2주차_우진/이분 그래프.java

✔ **연결 요소의 개수**, `11724`,  `실버2`, `DFS_BFS` 
✔ **이분 그래프**, `17071`, `골드4`,  `DFS_BFS`
✔ **단지번호붙이기**, `2667`, `실버1`, `DFS_BFS`

[22-09-15] Algorithm Study Merge

---

2주차/2주차_우진/README.md
2주차/2주차_우진/숨바꼭질.java
2주차/2주차_우진/숨바꼭질4.java

✔ 숨바꼭질, `1697`, `실버1`, `DFS_BFS`
✔ 숨바꼭질 4, `13913`, `골드4`, `DFS_BFS`

[22-09-17] Algorithm Study Merge

---

2주차/2주차_우진/README.md
2주차/2주차_우진/숨바꼭질 3.java
2주차/2주차_우진/알고스팟.java
2주차/2주차_우진/이모티콘.java

✔ 이모티콘, `14226`, `골드4`, `DFS_BFS`
✔ 숨바꼭질 3, `13549`, `골드5`, `DFS_BFS`
✔ 알고스팟, `1261`, `골드4`, `DFS_BFS`

[22-09-18] Algorithm Study Merge

---

3주차/3주차_우진/LCD Test.java
3주차/3주차_우진/README.md

✔ LCD Test, `2290`, `실버2`, `구현`

[22-09-22] Algorithm Study Merge

---

3주차/3주차_우진/README.md
3주차/3주차_우진/겉넓이 구하기.java
3주차/3주차_우진/정육면체 전개도.java

✔ 겉넓이 구하기, `16931`, `실버2`, `구현`
✔ 정육면체 전개도, `1917`, `골드1`, `구현`

[22-09-23] Algorithm Study Merge

---

4주차/4주차_우진/README.md
4주차/4주차_우진/두 동전.java
4주차/4주차_우진/에너지 모으기.java

✔ 두 동전, `16197`, `골드4`, `재귀`
✔ 에너지 모으기, `16198`, `실버1`, `재귀`

[22-09-28] Algorithm Study Merge

---

4주차/4주차_우진/README.md
4주차/4주차_우진/스타트와 링크.java
4주차/4주차_우진/연산자 끼워넣기(순열).java

✔ 연산자 끼워넣기, `14888`, `실버1`, `순열`
✔ 스타트와 링크, `14889`, `실버2`, `순열`

[22-10-01] Algorithm Study Merge

---

5주차/5주차_우진/README.md
5주차/5주차_우진/가르침.java
5주차/5주차_우진/부분수열의 합.java

✔ 부분수열의 합, `14225`, `실버1`, `비트마스크`
✔ 가르침, `1062`, `골드4`, `비트마스크`

[22-10-03] Algorithm Study MergeWoojin

---

5주차/5주차_우진/README.md
5주차/5주차_우진/구슬 탈출2.java

✔ 구슬 탈출 2, `13460`, `골드1`, `비트마스크`

[22-10-05] Algorithm Study MergeWoojin

---

5주차/5주차_우진/README.md
5주차/5주차_우진/두 스티커.java

✔ 두 스티커, `16937`, `실버3`, `브루트포스`

[22-10-07] Algorithm Study MergeWoojin

---

5주차/5주차_우진/README.md
5주차/5주차_우진/두 배열의 합.java
5주차/5주차_우진/부분수열의 합2.java

✔ 부분수열의 합2, `1208`, `골드1`, `이분탐색`
✔ 두 배열의 합, `2143`, `골드3`, `이분탐색`

[22-10-8] Algorithm Study Merge

---

6주차/6주차 우진/README.md
6주차/6주차 우진/서울 지하철 2호선.java
6주차/6주차 우진/육각보드.java

✔ 서울 지하철 2호선, `16947`, `골드3`, `그래프 이론`
✔ 육각보드, `12946`, `골드3`, `그래프 이론`

[22-10-12] Algorithm Study Merge

---

7주차/7주차 우진/README.md
7주차/7주차 우진/뱀과 사다리 게임.java

✔ 뱀과 사다리 게임, `16928`, `골드5`, `BFS/DFS`

[22-10-18] Algorithm Study Merge

---

7주차/7주차 우진/README.md
7주차/7주차 우진/데스 나이트.java
7주차/7주차 우진/연구소.java

✔ 데스나이트, `16948`, `실버1`, `BFS`
✔ 연구소, `14502`, `골드4`, `BFS`

[22-10-19] Algorithm Study Merge

---

7주차/7주차 우진/README.md
7주차/7주차 우진/돌 그룹.java
7주차/7주차 우진/벽 부수고 이동하기.java

✔ 돌 그룹, `12886`, `골드4`, `BFS`
✔ 벽 부수고 이동하기, `2206`, `골드4`, `BFS`

[22-10-21] Algorithm Study Merge

---

7주차/7주차 우진/README.md
7주차/7주차 우진/벽 부수고 이동하기4.java

✔ 벽 부수고 이동하기 4, `16946`, `골드2`, `BFS`

[22-10-22] Algorithm Study Merge

---

8주차/8주차 우진/README.md
8주차/8주차 우진/레이저 통신.java
8주차/8주차 우진/소수 경로.java
8주차/8주차 우진/적록색약.java

✔ 레이저 통신, `6087`, `골드3`, BFS
✔ 소수 경로, `1963`, `골드4`, BFS
✔ 적록색약, `10026`, `골드5`, BFS

[22-10-25] Algorithm Study Merge

---

8주차/8주차 우진/4 연산.java
8주차/8주차 우진/README.md
8주차/8주차 우진/스타트링크.java
8주차/8주차 우진/탈옥.java

✔ 4 연산, `14395`, `골드5`, `BFS`
✔ 스타트링크, `5014`, `골드5`, `BFS`
✔ 탈옥, `9376`, `플레5`, `BFS`

[22-10-26] Algorithm Study Merge

---

8주차/8주차 우진/README.md
8주차/8주차 우진/연구소 2.java
8주차/8주차 우진/연구소 3.java

✔ 연구소2, `17141`, `골드4`, `BFS`
✔ 연구소3, `17142`, `골드4`, `BFS`

[22-10-27] Algorithm Study Merge

---

9주차/9주차 우진/README.md
9주차/9주차 우진/이동하기.java

[22-10-31] Algorithm Study Merge

---

9주차/9주차 우진/1, 2, 3 더하기 4.java
9주차/9주차 우진/README.md

✔ 1, 2, 3 더하기4, `15989`, `실버`, `DP`

[22-11-01] Algorithm Study Merge

---

9주차/9주차 우진/README.md
9주차/9주차 우진/점프 점프.java
9주차/9주차 우진/팰린드롬.java

✔ 점프 점프, `11060`, `실버2`, `DP`
✔ 팰린드롬?, `10942`, `골드4`, `DP`

[22-11-02] Algorithm Study Merge
